### ISSUE TITLE
Unable to generate a random japanese-english pair

### ISSUE THREAD

**Issue by theoblivious** [theoblivious/Animania#6]
My MVP is nearly complete.  I am having an issue of randomly grabbing a Japanese word and then displaying the english equivalent when I press show English.  I have tried a number of different ways but have had no success. Currenlty it is stuck as only grabbing the first values (I've tried to grab random samples but have had no success) .  

Ive updated github my most recent test file. I'd take a look at:

show_english.html.erb in questions
show_japanese.html.erb in questions
show.html.erb for anime
Questions Controller, show method. 

Any help on this would be really great!

**Comment by jrhorn424** [comment]
It's good practice to include code examples.

**Comment by jrhorn424** [comment]
Like this:

``` ruby
class Bar < Foo
  def baz
    puts 'qux'
  end
end
```

**Comment by jrhorn424** [comment]
Use rails until it hurts.
